name: Integration Test

on:
  workflow_dispatch:
    # Manual trigger with no inputs required

permissions:
  id-token: write # Required for Azure login with OIDC
  contents: read  # Required to checkout code

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: '7.2'
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup GitHub CLI
        run: |
          gh --version
          gh auth status || gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
          echo "GitHub CLI authenticated successfully"
        shell: bash
        
      - name: Install required PowerShell modules
        run: |
          pwsh -Command "Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force"
          echo "PowerShell modules installed successfully"
        
      - name: Run Integration Test
        run: |
          cd ${{ github.workspace }}
          pwsh -Command "Write-Host 'Starting integration test' -ForegroundColor Green"
          pwsh -Command "./integration-tests/Invoke-IntegrationTest.ps1"
        
      - name: Clean up resources on completion
        if: ${{ always() }}
        run: |
          cd ${{ github.workspace }}
          pwsh -Command "Write-Host 'Starting cleanup' -ForegroundColor Yellow"
          pwsh -Command "./integration-tests/Invoke-IntegrationTest.ps1 -Cleanup"