name: Publish PowerShell Module

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Import-Module ./az-bootstrap.psd1 -Force
          Invoke-Pester -Path ./tests

      - name: Publish to PowerShell Gallery
        if: github.event_name == 'release'
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          Publish-Module -Path . -NuGetApiKey $env:NUGET_API_KEY -Verbose